apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojipedia
  labels:
    app: emojipedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emojipedia
  template:
    metadata:
      labels:
        app: emojipedia
    spec:
      containers:
        - name: reactjs
          image: jazzjohn/emojipedia:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-app-service
spec:
  type: NodePort
  selector:
    app: emojipedia
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30003